### ISSUE TITLE
$order->get_payment_method_title() doesent return string

### ISSUE THREAD

**Issue by PT-WP** [teambank/ratenkaufbyeasycredit-plugin-woocommerce#1]
$order->get_payment_method_title()
Is is empty if paid with easyCredit?

**Comment by netzkollektiv** [comment]
I'm sorry, I can't understand your problem. Please provide a complete example and elaborate on what you trying to achieve.

**Comment by PT-WP** [comment]
Sry, changed the title of the issue. To get the Name (not ID or Slug) of the payment method there is a default WooCommerce function "$order->get_payment_method_title()" which should return "easyCredit" in your case.

But this is empty. Nothing is returning.
So it's not possible to display the payment method name in something like a invoice.

**Comment by PT-WP** [comment]
I try to get the payment method title in my own development. I am just using the function I already mentioned.
$order->get_payment_method_title() to get the name of payment method.

Did you tried this?

**Comment by netzkollektiv** [comment]
I'm sorry, I do not know how to help without context. As this seems not be an issue with the plugin itself but rather with custom programming I'm closing this issue. Please get in touch with the support team as suggested above.

**Comment by dkrebs** [comment]
Here is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) which proves that the function is working as expected:
```
<?php
define( 'BASE_PATH', dirname(__FILE__) ."/" );
define('WP_USE_THEMES', false);
global $wp, $wp_query, $wp_the_query, $wp_rewrite, $wp_did_header;
require(BASE_PATH . 'wp-load.php');

$order = wc_get_order(772);
echo $order->get_id().PHP_EOL;
echo $order->get_payment_method_title().PHP_EOL;
```

Save it as `test.php`, adjust the order_id and you should get the following output:

> 772
> easyCredit-Ratenkauf

**Comment by netzkollektiv** [comment]
Here is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) which proves that the function is working as expected:
```
<?php
define( 'BASE_PATH', dirname(__FILE__) ."/" );
define('WP_USE_THEMES', false);
global $wp, $wp_query, $wp_the_query, $wp_rewrite, $wp_did_header;
require(BASE_PATH . 'wp-load.php');

$order = wc_get_order(772);
echo $order->get_id().PHP_EOL;
echo $order->get_payment_method_title().PHP_EOL;
```

Save it as `test.php`, adjust the order_id and you should get the following output:

> 772
> easyCredit-Ratenkauf
