### ISSUE TITLE
Overwrite CSS from Widget

### ISSUE THREAD

**Issue by PT-WP** [teambank/ratenkaufbyeasycredit-plugin-woocommerce#2]
How I can overwrite the CSS of Widgets from the Plugin?

**Comment by netzkollektiv** [comment]
The web components are document here:
https://netzkollektiv.com/docs/easycredit-ratenkauf-components/

As the components are using a Shadow DOM, CSS properties can only be overwritten using JavaScript. If the shadow around the widget bothers you, there is also the option of adding the attribute "display-type="clean" to the widget <easycredit-widget.

Further changes are possible by manipulating the shadow DOM:
https://stackoverflow.com/questions/47625017/override-styles-in-a-shadow-root-element
You are then largely free in the design and can use CSS for the design.
